# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04b0e61b2415ce7bb2371d27e0334920d13ff5d55ee45d9dfe0667a2afefdf4ca93537f07eab1e2a05cb072a95e46b414ebfa91129a88c4d925553cf5fdddb2b

test:
  secret_key_base: d8563203bcf4c97c71fb3ed1c20c7cb7c8a9b275a416c497cb30403733f6e05712bf8a5f2e210f23aa1f2e25e609ea59f402a38362ed5b8c49837e232f0d617a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
